from src.envs.reward_modifiers.ladder_incentive import LadderIncentive
from src.envs.reward_modifiers.level_incentive import LevelIncentive
from src.envs.reward_modifiers.magic_stars import MagicStarsIncentive
from src.envs.reward_modifiers.punish_death import PunishDeath
from src.envs.reward_modifiers.punish_needless_jump import PunishNeedlessJump
